<script setup lang="ts">
import type { LanguageId, LanguageOption } from '~/types/game'

const game = useGameClient()
const router = useRouter()
const config = useRuntimeConfig()
const appBaseUrl = computed(() => String(config.public.appBaseUrl || '').replace(/\/$/, ''))
const landingUrl = computed(() => absolutePublicUrl('/'))
const landingOgImage = computed(() => absolutePublicUrl('/og/default.png'))

const languages = ref<LanguageOption[]>([])
const selectedLanguage = ref<LanguageId>('js')
const loading = ref(true)
const starting = ref(false)
const error = ref('')
const showProfileStep = ref(false)
const enableProfileStep = ref(false)
const profileCodingExperience = ref('')
const profileAiToolUsage = ref('')

useSeoMeta({
  title: 'The Authorship Tribunal',
  description: 'Inspect ten code exhibits and decide whether each one came from a human or AI.',
  ogTitle: 'The Authorship Tribunal',
  ogDescription: 'A developer-facing code reading game with ten cases, no login, and a sealed court record.',
  ogUrl: landingUrl,
  ogImage: landingOgImage,
  twitterCard: 'summary_large_image',
  twitterTitle: 'The Authorship Tribunal',
  twitterDescription: 'Inspect ten code exhibits and decide whether each one came from a human or AI.',
  twitterImage: landingOgImage
})

onMounted(async () => {
  const stored = game.getStoredRun()
  if (stored) {
    await router.replace(`/quiz/${stored.sessionId}`)
    return
  }

  try {
    const response = await game.getLanguages()
    languages.value = response.languages
    enableProfileStep.value = response.featureFlags.enableDemographicPrompts
    selectedLanguage.value = response.languages.find((language) => language.enabled)?.id || 'js'
  } catch {
    error.value = 'Could not load the quiz setup. The console has been informed, probably too dramatically.'
  } finally {
    loading.value = false
  }
})

const enabledLanguages = computed(() => languages.value.filter((language) => language.enabled))

async function start() {
  error.value = ''
  if (enableProfileStep.value && !showProfileStep.value) {
    showProfileStep.value = true
    return
  }

  starting.value = true
  try {
    const session = await game.startSession({
      language: selectedLanguage.value,
      profileCodingExperience: profileCodingExperience.value || undefined,
      profileAiToolUsage: profileAiToolUsage.value || undefined
    })
    await router.push(`/quiz/${session.sessionId}`)
  } catch {
    error.value = 'Could not start a round. The dataset may not have enough approved pairs yet.'
  } finally {
    starting.value = false
  }
}

function absolutePublicUrl(path: string) {
  return appBaseUrl.value ? `${appBaseUrl.value}${path}` : path
}
</script>

<template>
  <main id="main" class="court court-landing">
    <TribunalHeader />

    <template v-if="!showProfileStep">
      <section class="landing-layout">
        <div class="landing-copy">
          <p class="kicker">10 cases. No login. No hints.</p>
          <h2>The council awaits your ruling.</h2>
          <p class="lede">
            Pick one language, examine ten normalized exhibits, and decide whether each
            record was written by hand or generated by machine.
          </p>
          <div class="briefing-strip" aria-label="Court rules">
            <span>10 mandatory rulings</span>
            <span>Results disclosed after</span>
          </div>
        </div>

        <aside class="exhibit landing-exhibit" aria-label="Evidence preview">
          <div class="exhibit-tag">
            <span class="label">Exhibit preview</span>
            <span>Unlabelled · JavaScript</span>
          </div>
          <pre class="code-panel mini-code"><code><span class="ln"><span class="kw">function</span> <span class="fn">verdict</span>(sample) {</span>
<span class="ln">  <span class="kw">const</span> tells = <span class="fn">read</span>(sample)</span>
<span class="ln">  <span class="kw">return</span> tells.score &gt; <span class="num">2</span></span>
<span class="ln">    ? <span class="str">"human"</span></span>
<span class="ln">    : <span class="str">"machine"</span></span>
<span class="ln">}</span></code></pre>
        </aside>
      </section>
    </template>

    <section v-else class="panel profile-panel">
      <p class="kicker">Optional voir dire</p>
      <h2>Two context notes, both skippable.</h2>
      <div class="controls controls-spaced">
        <select
          v-model="profileCodingExperience"
          class="select"
          aria-label="Coding experience"
          name="coding-experience"
          autocomplete="off"
        >
          <option value="">Which best describes you?</option>
          <option value="professional">Professional developer</option>
          <option value="hobbyist_student">Hobbyist or student</option>
          <option value="dont_code_regularly">I do not code regularly</option>
          <option value="prefer_not_to_say">Prefer not to say</option>
        </select>
        <select
          v-model="profileAiToolUsage"
          class="select"
          aria-label="AI tool usage"
          name="ai-tool-usage"
          autocomplete="off"
        >
          <option value="">How often do you use AI coding tools?</option>
          <option value="daily">Daily</option>
          <option value="sometimes">Sometimes</option>
          <option value="rarely_never">Rarely or never</option>
          <option value="prefer_not_to_say">Prefer not to say</option>
        </select>
      </div>
    </section>

    <section class="panel convene-panel">
      <div class="controls">
        <select
          v-model="selectedLanguage"
          class="select"
          aria-label="Programming language"
          name="language"
          autocomplete="off"
          :disabled="loading || starting"
        >
          <option v-for="language in enabledLanguages" :key="language.id" :value="language.id">
            {{ language.name }}
          </option>
        </select>
        <button class="btn primary" :disabled="loading || starting || enabledLanguages.length === 0" @click="start">
          {{ starting ? 'Convening…' : 'Convene the council' }}
        </button>
        <button
          v-if="showProfileStep"
          class="btn"
          :disabled="starting"
          @click="profileCodingExperience = ''; profileAiToolUsage = ''; start()"
        >
          Skip
        </button>
      </div>
      <p v-if="enabledLanguages.length === 0 && !loading" class="error mt-12">
        No language has enough approved pairs yet.
      </p>
      <p v-if="error" class="error mt-12">{{ error }}</p>
    </section>
  </main>
</template>
